export const randomCommentList = [
  "Wow!",
  "Amazing!",
  "Stunning!",
  "Incredible!",
  "Love it!",
  "Masterpiece!",
  "Brilliant!",
  "Fantastic!",
  "Awesome!",
  "Impressive!",
  "Epic!",
  "Marvelous!",
  "Superb!",
  "Wonderful!",
  "Brilliant!",
  "Fabulous!",
  "Excellent!",
  "Magnificent!",
  "Splendid!",
  "Terrific!",
];
